### ISSUE TITLE
Support of `ipfs dag ...`

### ISSUE THREAD

**Issue by mckingho** [ipfs-shipyard/py-ipfs-http-client#130]
Hi,
I cannot find a function to dag put. It would be nice to have these interface supported. Thanks.
https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DAG.md

**Comment by whereswaldon** [comment]
Hello @mckingho! We actually do not have an implementation of those yet, but it would be easy to add it. Would you be interested in helping to implement those?

**Comment by jonnycrunch** [comment]
@whereswaldon this is trivial with the requests module:   

import requests
resp = requests.get("http://localhost:5001/api/v0/dag/get?arg=<cid>") 
data =.resp.json()

**Comment by meyer1994** [comment]
I've created a PR #231 that adds `dag` support to the client. Criticism is welcome :)

**Comment by ntninja** [comment]
@meyer1994 has implemented this! :smiley_cat:
