### ISSUE TITLE
Remove the py-ipfs-http-client branch

### ISSUE THREAD

**Issue by AliabbasMerchant** [ipfs-shipyard/py-ipfs-http-client#195]
@alexander255 Shall we drop the branch? (And possibly other not-needed branches too)

There are a few commit differences in master and py-ipfs-http-client branch, although

**Comment by Swixx** [comment]
@alexander255 @AliabbasMerchant can there be a general cleanup of this repo? Specifically, I think seeing stale issues from 2016 may dissuade potential contributors.

**Comment by alexander255** [comment]
All branches other then `py-ipfs-api` and `master` can be removed yes. I've triaged many issues and closed several (some 2016 issues remain, that simply never have been fixed).

**Comment by alexander255** [comment]
… Done
