### ISSUE TITLE
optional parameters are not supported by some endpoints

### ISSUE THREAD

**Issue by jacopo-massa** [ipfs-shipyard/py-ipfs-http-client#202]
from [HTTP API](https://docs.ipfs.io/reference/api/http/)

`/api/v0/swarm/peers` can have some boolean arguments. Why can't I specify them when i invoke
`client.swarm.peers`?

**Comment by alexander255** [comment]
@jacopo-massa: The API endpoints change over time and the *py-ipfs-api-client* developers are mostly engaged in other projects right now, so it's simply a matter of nobody having added these attributes yet. That said, we would absolutely welcome some contributions in this area.

Unlike many other things adding missing attributes fortunately is dead-simple:

 1. Find the method that is missing some attribute: https://github.com/ipfs/py-ipfs-http-client/blob/master/ipfshttpclient/client/swarm.py#L171-L194
 2. Add the pythonized attribute names to the function signature: `…, *, verbose: bool = False, streams: bool = False, latency: bool = False, direction: bool = False, **kwargs): …`
 3. And documentation for each parameter in the comment section below
 4. Inject the HTTP variant of each parameter as a dict to be passed to the HTTP layer: `kwargs.setdefault("opts", {"verbose": verbose, "stream": streams, "latency": latency, "direction": direction})`
 5. Some basic unit test (querying the API with different parameters and checking that the results look sane) would be appreciated

While there is obviously quite some backlog in this project right now, PRs such as this will still be reviewed and most likely approved quite quickly.

**Comment by jacopo-massa** [comment]
Thanks for the clarifying and exhaustive answer. I’ll try to help following your suggestions!

**Comment by ntninja** [comment]
@jacopo-massa: Did you end up implementing anything?

**Comment by jacopo-massa** [comment]
> @jacopo-massa: Did you end up implementing anything?

Not yet, I worked on other project and used the HTTP API's for IPFS
