### ISSUE TITLE
Is it possible to check the given ipfs-hash is valid or not?  [help, request]

### ISSUE THREAD

**Issue by avatar-lavventura** [ipfs-shipyard/py-ipfs-http-client#225]
Based on the creating ipfs hash algorithm(https://ethereum.stackexchange.com/a/53233/4575 1), how can I check the given ipfs-hash is valid or not?

Is there any function under `py-ipfs-http-client` that I can accomplish it?

**Comment by ntninja** [comment]
What do you mean by “valid”, exactly? If you want check whether a given text or binary string is syntactically a valid CID (multibase prefix + multicodec type + hash type + hash length + hash value), I'd recommend trying to parse it with the [`py-cid`](https://github.com/ipld/py-cid) library's `make_hash` function and checking whether you get an exception or not. If it returns successfully you also check whether the returned codec type and hash type match what you expect to do some semantic validation.

If you actually want to know if there exists any piece of content for the given CID, then your out of luck. The only way to find that out is to simply try requesting the value of the network and hope that you get a valid response.

**Comment by avatar-lavventura** [comment]
Good catch I was able to check it with the following code:

```
from cid import make_cid

def is_valid(ipfs_hash: str) -> bool:
    try:
        make_cid(ipfs_hash)
	return True
    except:
        return False
```
