### ISSUE TITLE
`cid_version` parameter for client.add

### ISSUE THREAD

**Issue by SupraSummus** [ipfs-shipyard/py-ipfs-http-client#226]
Could you please add support for `cid_version` parameter in `client.add` method? The option is available in ipfs CLI (https://docs.ipfs.io/reference/cli/#ipfs-add), but not thorough ipfs-http-client.

Thanks

**Comment by ntninja** [comment]
In general we prefer community contributions for these simple tasks. Hence, could you add it instead? You'd just need to add the relevant option to [`client.add`](https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/637adbd479283ae872d55e3b99bd87e87771db6b/ipfshttpclient/client/files.py#L234-L365) and map it to the respective [HTTP API parameter](https://docs.ipfs.io/reference/http/api/#api-v0-add) similar to the existing code.

There'll also have to be a test in [`test/function/test_files.py`](https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/637adbd479283ae872d55e3b99bd87e87771db6b/test/functional/test_files.py), but just adding a file CID version 0 and 1 and comparing the the correct CID is returned in each case would be good-enough.

Do you think this is something you could do?

**Comment by SupraSummus** [comment]
Yep, I will take a shot at this.

**Comment by ntninja** [comment]
Thanks for submitting PRs for small stuff like this, it really helps!

Do you have any short-term need for this to be released?

**Comment by SupraSummus** [comment]
Glad I could help.

This is not very urgent. I need this for more elegant test suite in [ipfs-api-mount](https://github.com/SupraSummus/ipfs-api-mount).

**Comment by ntninja** [comment]
Ok. It may be anywhere between one and a couple of weeks before I release this then, I'm currently working on some big long-overdue tasks around here.
