### ISSUE TITLE
requests backend sets unused `session.timeout` attribute

### ISSUE THREAD

**Issue by SupraSummus** [ipfs-shipyard/py-ipfs-http-client#230]
When constructing ipfs client you can pass `timeout=5`, and it will be added to requests Session object. Code responsible is around here:
https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/d008914de96467c66fb67ed6da6d45067a828be2/ipfshttpclient/http_requests.py#L78-L106

However, as far as I understand requests, `session.timeout` is never used. Timeout has to be passed for each request. (Or have I missed something?)

If I'm right then it may be a good idea to indicate to the user that `timeout` kwarg is ignored. (I volunteer to do it.)

**Comment by ntninja** [comment]
Thank you for your detailed report! That was indeed a bug in the requests backend. :slightly_smiling_face:
