### ISSUE TITLE
bug/info: TypeError: Plain typing.NoReturn is not valid as type argument

### ISSUE THREAD

**Issue by thelostone-mc** [ipfs-shipyard/py-ipfs-http-client#235]
#### Description

Travis setup seems to be failing after we got the latest version 0.6.1

![image](https://user-images.githubusercontent.com/5358146/92187692-18eea280-ee78-11ea-8fbc-efb6690c977c.png)

![image](https://user-images.githubusercontent.com/5358146/92187641-f8264d00-ee77-11ea-8bd8-7a2ddb171d45.png)

package being used:
https://github.com/gitcoinco/web/blob/master/requirements/base.txt#L44

go-ipfs being used:
https://github.com/gitcoinco/web/blob/master/docker-compose.yml#L45

Any leads on what one could do to get past these ?

**Comment by SupraSummus** [comment]
It is a [bug in python](https://bugs.python.org/issue34921). Newer pythons (>=3.7.2) should be okay with this.

**Comment by SupraSummus** [comment]
@thelostone-mc in my travis config I fixed it this way: https://github.com/SupraSummus/ipfs-api-mount/commit/fb2d66d960c455a08327ecc68fadf3b55c8f5766

**Comment by ntninja** [comment]
Thanks for figuring that out, I'd be curious to know why it didn't fail on our CI tests (also Travis).

@SupraSummus: Could you try setting `dist: bionic` in the Travis config and see if this makes the issue also disappear? For `dist: xenial` the `virtualenv` package was too old to run our tests, so I had ditched it some time ago.

**Comment by SupraSummus** [comment]
Setting `dist: focal` resolves the issue. Haven't checked `dist: bionic`.

So it seems that under `dist: xenial` (default) "python 3.7" means "python 3.7.1". (Kinda strange, but I come from arch-linux-rolling-distro lands, so I might be skewed here.)

**Comment by ntninja** [comment]
Well Ubuntu xenial [shipped with 3.5.1 by default](https://packages.ubuntu.com/xenial/python3), so if your problem domain includes “should run OOTB on Ubuntu xenial” the behaviour makes sense. If you don't care about that and only want to test the latest versions on each series… Not so much.

Anyways, I “fixed” this problem on master by explicitly banning incompatible Python subversions in the 3.5, 3.6 and 3.7 branches. So hopefully people will see a clear error message now when they test their code on Travis' Python 3.7 and similar things.
