### ISSUE TITLE
IPNS Timing out Error

### ISSUE THREAD

**Issue by crossoveranx** [ipfs-shipyard/py-ipfs-http-client#237]
I'm trying to publish a file using a local IPFS node using IPNS, however it consistently times out. I'm currently using the following as a short test:

  ```  
    client = ipfshttpclient.connect('/dns/ipfs/tcp/5001')
    #I have also tried /ipns/
    tempAddress = '/ipfs/QmNVbGwachkfbnimSc59twHpo9b9bwYzi8QTyMoRNzM9VY'
    ipnshash = client.name.publish(tempAddress, key="self")
```

Any ideas on how to publish an existing IPFS file to IPNS via this library?

**Comment by ntninja** [comment]
As per [the documentation](http://ipfs.io/ipns/12D3KooWEqnTdgqHnkkwarSrJjeMP2ZJiADWLYADaNvUb6SQNyPF/docs/http_client_ref.html#the-api-client), please try setting the *timeout* parameter to some large value (such as 300 or 600 seconds) and see if it helps. IPNS can be slow and IPNS name publishing much more so.

**Comment by crossoveranx** [comment]
Awesome, thanks for the info - set the timeout to 300 seconds. Still takes a long time, but it works!
