### ISSUE TITLE
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.7.0' (not in range: 0.4.22 ≤ … < 0.7.0)

### ISSUE THREAD

**Issue by hicetnunc2000** [ipfs-shipyard/py-ipfs-http-client#239]
I ran into this error from this code:
```
import ipfshttpclient
conn = ipfshttpclient.connect('/dns4/ipfs.infura.io/tcp/5001/https')
```
I'm using ```python 3.8.2, ipfshttpclient 0.6.1```.
even though it was working some days ago I'm wondering if there were any updates on go-ipfs/infura and if there is a way to adapt the package.

**Comment by njgheorghita** [comment]
We're also blocked by this error in [web3.py](https://github.com/ethereum/web3.py/pull/1757). It appears to me that Infura recently updated their IPFS endpoint to version `7.0`, causing this error when you try to connect to their provider.

**Comment by hicetnunc2000** [comment]
I've managed to connect with ipfs with an old ipfs-js-client though lol in case anyone is under some urgency

**Comment by marcgarreau** [comment]
:wave: @ntninja @meyer1994 is #241 an acceptable solution?

**Comment by ntninja** [comment]
Sorry for the delay! Version 0.7.0a1 fixes this for the time being until all the changes for the 0.7.0 version have completed. (The 0.7.0 release may include some backward-incompatible changes from 0.7.0a1).
