### ISSUE TITLE
/api/v0/version is not whitelisted by some public endpoints

### ISSUE THREAD

**Issue by p4bl0-** [ipfs-shipyard/py-ipfs-http-client#243]
Hello :),

The `connect` function of the `ipfshttpclient` module makes a request to `/api/v0/version` which fails with a HTTP 403 error on some IPFS API endpoints which do not whitelist access to `/api/v0/version`.

This prevent the use of py-ipfs-http-client with these endpoints.

It seems the JavaScript and Go IPFS HTTP library do not make this request, so it is probably not mandatory in the protocol and just used for some verifications by this Python package.

Maybe it should be possible to have an argument to prevent this request?

In the `connect` function the request is made by the call to `client.apply_workarounds` which in turn calls `self.version` which does the request.

Maybe an alternative would be to provide the version number manually to the `connect` function for example? This way the version number could be passed to `apply_workaround` which would use it rather that calling `self.version`.

**Comment by ntninja** [comment]
> Maybe an alternative would be to provide the version number manually to the connect function for example? This way the version number could be passed to apply_workaround which would use it rather that calling self.version.

Genuine Question: How would your script know the version number if not by querying the endpoint when connecting to such a service?

> It seems the JavaScript and Go IPFS HTTP library do not make this request, so it is probably not mandatory in the protocol and just used for some verifications by this Python package.

There is no specific sequence of requests required by the protocol at all, so you are right on that. However `version` is supposed to exist even in the read-only protocol variant and `py-ipfs-http-client` simply expects that feature to present as it should be, so the current behaviour isn't *wrong* either. (See next question for the semi-official workaround.)

> Maybe it should be possible to have an argument to prevent this request?

You can manually construct the `Client` object using `ipfshttpclient.Client(<mostly same args as connect>)` to bypass probing the API provider entirely and use defaults. This isn't really a supported configuration, but it should work unless some major changes are done to the relevant read-only parts of the API (very unlikely).
If you do this however, please also try to get in touch with your API provider and ask them why they actually block that call – most likely they just didn't consider it when writing their rules, but if it was on purpose it be interesting to know what their rationale is.

**Comment by p4bl0-** [comment]
> How would your script know the version number if not by querying the endpoint when connecting to such a service?

I don't know, I suppose I could ask the API provider. But it is not very robust indeed.

> please also try to get in touch with your API provider and ask them why they actually block that call.

Okay, I will do that.

> You can manually construct the `Client` object using `ipfshttpclient.Client(<mostly same args as connect>)`.

Thanks, I will try that meanwhile.

**Comment by ntninja** [comment]
> > please also try to get in touch with your API provider and ask them why they actually block that call.
> 
> Okay, I will do that.

Thanks! I'll close this issue in the meantime as it's technically not our fault. But please, do report your findings once you get a reply!
