### ISSUE TITLE
Current documentation seems to be unavailable?

### ISSUE THREAD

**Issue by johnxx** [ipfs-shipyard/py-ipfs-http-client#244]
I can't seem to get the docs to load either via the ipfs.io gateway or directly from my go-ipfs node using `ipfs resolve /ipns/12D3KooWEqnTdgqHnkkwarSrJjeMP2ZJiADWLYADaNvUb6SQNyPF/docs/`. Please let me know if there's some other debugging information I could add to help track this down.

**Comment by ntninja** [comment]
This should have been resolved some time between your issue and now. Hopefully it stays that way for some time. Thanks for the report and sorry for the general slowness of responses!

**Comment by johnxx** [comment]
No worries on the late response. I know how life gets in the way. I'm just glad to see you're still checking in since I've started using this for small project I'm working on. :) Anyways, loading the docs now works for me through the gateway and directly via my local IPFS node, so I think the issue can be closed.

**Comment by ntninja** [comment]
Thank you for the kind words! There is actually a large feature (async & typing) in the works right now, but could be anywhere between days and weeks depending on how the timing plays out. Code is pretty much done but I haven't figured out how to do proper testing and docs yet. I don't think I'll be leaving too soon, no worries. ;-)
