### ISSUE TITLE
pip package doesn't work with latest ipfs daemon

### ISSUE THREAD

**Issue by kovan** [ipfs-shipyard/py-ipfs-http-client#248]
The version of this package in pip repository is 0.6.1, which doesn't work with latest official ipfs release:

`
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.7.0' (not in range: 0.4.22 ≤ … < 0.7.0)`

$ ipfs --version
`ipfs version 0.7.0`

If I install from source it does work. New release needed?

**Comment by andrewjaanuu** [comment]
+1

**Comment by andrewchen5678** [comment]
+1

**Comment by SupraSummus** [comment]
You can install pre release using `pip install --pre ipfshttpclient==0.7.0a1`. It supports go-ipfs 0.7.x but not go-ipfs 0.8.x.

@ntninja could you please push a non-pre release? Or are there any blockers?

**Comment by veqtor** [comment]
Ridiculous, latest IPFS is 0.8.0

**Comment by ntninja** [comment]
Well, this one is fixed and next one is already open…
