### ISSUE TITLE
Unbreak the mypy tests

### ISSUE THREAD

**Issue by dokterbob** [ipfs-shipyard/py-ipfs-http-client#255]
Making it easier to make (for contributors) and accept (for maintainers) contributions.

**Comment by ntninja** [comment]
mypy stuff breaks with like every second update, but it should be fixed again I agree.

**Comment by ntninja** [comment]
Want to delay this until after 0.8 since it's likely a lot of work.

**Comment by c0llab0rat0r** [comment]
> Want to delay this until after 0.8 since it's likely a lot of work.

This will be significantly less work if the minimum Python version is raised to 3.7. https://github.com/ipfs-shipyard/py-ipfs-http-client/issues/258

**Comment by c0llab0rat0r** [comment]
If #257 and #260 are merged, it would resolve this issue.

**Comment by c0llab0rat0r** [comment]
@ntninja with the merge of #261, I believe this is now resolved, though there is more work to do to remove type hint warning suppression.

**Comment by ntninja** [comment]
Yes it can be better or course, but it a much better situation than what we started out with thanks to you!
