### ISSUE TITLE
VersionMismatch: Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)

### ISSUE THREAD

**Issue by iskanderandrews** [ipfs-shipyard/py-ipfs-http-client#275]
Hi, 
I'm trying to connect with local ipfs daemon, but getting this error. 
`ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)`

```bash 
$ ipfs daemon 
```

```
Initializing daemon...
go-ipfs version: 0.8.0-ce693d7e8
Repo version: 11
System version: amd64/linux
Golang version: go1.16.2
2021/04/30 07:30:58 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/udp/4001/quic
Swarm listening on /ip4/192.168.1.104/tcp/4001
Swarm listening on /ip4/192.168.1.104/udp/4001/quic
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic
Swarm listening on /ip6/fd74:ae1:c698:db00:da5c:3a2c:f128:5c03/tcp/4001
Swarm listening on /ip6/fd74:ae1:c698:db00:da5c:3a2c:f128:5c03/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/192.168.1.104/tcp/4001
Swarm announcing /ip4/192.168.1.104/udp/4001/quic
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8081
Daemon is ready

```

```bash 
$ pip show ipfshttpclient  
```

```
Name: ipfshttpclient
Version: 0.7.0
Summary: Python IPFS HTTP CLIENT library
Home-page: https://ipfs.io/ipns/12D3KooWEqnTdgqHnkkwarSrJjeMP2ZJiADWLYADaNvUb6SQNyPF/
Author: py-ipfs-http-client team
Author-email: 
License: MIT License
Location: /home/isk/Projects/Blockboard/ipfs-opensea-uploader/env-ipfs/lib/python3.9/site-packages
Requires: requests, multiaddr
Required-by: 

```

- OS information: 
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

```
- _go-ipfs_: 
`ipfs version 0.8.0`

- Python: 
`Python 3.9.4`

- pip
`pip 21.1`

Thanks for help!

**Comment by iskanderandrews** [comment]
I downgraded `ipfs` to `v0.7.0` and it worked successfully.

**Comment by c0llab0rat0r** [comment]
The current library doesn't support v0.8.0 yet. #274 needs to get resolved first.

v8 support was first mentioned in issue #252.

**Comment by iskanderandrews** [comment]
> The current library doesn't support v0.8.0 yet. #274 needs to get resolved first.
> 
> v8 support was first mentioned in issue #252.

Thanks so much for your response. 

I opened this PR #276 for updating the README documentation until this issue #274 gets resolved.

**Comment by c0llab0rat0r** [comment]
Version `0.8.0a1` has been published to PyPi.

**Comment by ntninja** [comment]
Thank you :grinning:

**Comment by AbhigyaWangoo** [comment]
How did you guys downgrade your ipfs version? I'm getting a version mismatch on version 0.13.1

**Comment by Admski** [comment]
SOLUTION!: 
What worked for me on mac 13.2.1 was de-installing ipfs completely from the system. Deleting all files on /usr/local/bin. After that install ipfs version 0.7.0. This was working and looked like this:

Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4

**Comment by valkiriaaquatica** [comment]
Hey everyone that is maybe has the same issue as me using the follwing:
ipfs verion: 0.24.0
python 3.8 
ipfshttpclient 0.7.0
os: ubuntu 22.04 jammy
golang: 1.21.6

The solution is to downgrade the ipfs verison to: ipfs version 0.7.0
