### ISSUE TITLE
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.11.0' (not in range: 0.4.23 ≤ … < 0.8.0)

### ISSUE THREAD

**Issue by asafd11** [ipfs-shipyard/py-ipfs-http-client#310]
any idea how to fix this?

**Comment by pintman** [comment]
same here

**Comment by veqtor** [comment]
this project is abandoned more or less

**Comment by kasteph** [comment]
This actually looks like a duplicate of #313 and it seems to be an ongoing problem whenever kubo upgrades. For any ongoing discussions/issues for this topic, I'd like to defer to the other issue so that it's easier to have the info in one place and focus.

Thanks.
